// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCELZUB4BzaezA4rZiYMERuQ6DF40ULL_A',
    appId: '1:272504469517:web:f2091f23bf7c564cbdbd44',
    messagingSenderId: '272504469517',
    projectId: 'ledwoki',
    authDomain: 'ledwoki.firebaseapp.com',
    databaseURL: 'https://ledwoki-default-rtdb.firebaseio.com',
    storageBucket: 'ledwoki.firebasestorage.app',
    measurementId: 'G-S8GBZ6SDZ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8N0-O7DG9B2sf0seLfU9khnT5lGqgJK8',
    appId: '1:272504469517:android:6bac215e5dd03f2fbdbd44',
    messagingSenderId: '272504469517',
    projectId: 'ledwoki',
    databaseURL: 'https://ledwoki-default-rtdb.firebaseio.com',
    storageBucket: 'ledwoki.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbpqDtodnEb1mPYL3aEkVXavlh3vLT-jg',
    appId: '1:272504469517:ios:b4b0ce85d1a63c8dbdbd44',
    messagingSenderId: '272504469517',
    projectId: 'ledwoki',
    databaseURL: 'https://ledwoki-default-rtdb.firebaseio.com',
    storageBucket: 'ledwoki.firebasestorage.app',
    iosBundleId: 'com.example.tranca',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbpqDtodnEb1mPYL3aEkVXavlh3vLT-jg',
    appId: '1:272504469517:ios:b4b0ce85d1a63c8dbdbd44',
    messagingSenderId: '272504469517',
    projectId: 'ledwoki',
    databaseURL: 'https://ledwoki-default-rtdb.firebaseio.com',
    storageBucket: 'ledwoki.firebasestorage.app',
    iosBundleId: 'com.example.tranca',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCELZUB4BzaezA4rZiYMERuQ6DF40ULL_A',
    appId: '1:272504469517:web:b1d47c23eb2de464bdbd44',
    messagingSenderId: '272504469517',
    projectId: 'ledwoki',
    authDomain: 'ledwoki.firebaseapp.com',
    databaseURL: 'https://ledwoki-default-rtdb.firebaseio.com',
    storageBucket: 'ledwoki.firebasestorage.app',
    measurementId: 'G-SLHYEY6PYZ',
  );
}
